sudo: false
branches:
  only:
  - pelican
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_a820959e829e_key -iv $encrypted_a820959e829e_iv -in publish-key.enc -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git remote set-url origin git@github.com:drgarcia1986/blog.git
- git fetch origin -f gh-pages:gh-pages
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make github
